entities:
- name: test
  metadata:
    organization: hashicorp1
    team: vault
  policies:
  - default
- name: foo
  metadata:
    organization: hashicorp1
    team: vault
  policies:
  - default
entitiesAliases:
- name: test
  authBackEnd: token/
  entityNameRef: test
- name: foo
  authBackEnd: token/
  entityNameRef: foo
  
